"""Fill Banking77's gap: it has no "goods/services not received" intent. Generate short support messages in
Banking77's style for DisputeType.not_received, deduplicated, with review_status="unreviewed".

    uv run python scripts/generate_router_synthetic.py --n 300
    -> data/synthetic/not_received.jsonl  (committed: small, synthetic, reviewable)

Leakage note: these are generated by an LLM, so the router's test metrics for not_received are reported
separately from Banking77's human-written classes (see PLAN.md).
"""

from __future__ import annotations

import argparse
import json
import random
import re
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from dotenv import load_dotenv
from pydantic import BaseModel

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
load_dotenv(ROOT / ".env")

from dispute_agent.config import Settings  # noqa: E402
from dispute_agent.llm_brain import make_llm_brain  # noqa: E402


class Batch(BaseModel):
    messages: list[str]


EXAMPLES = ["A transaction shows duplicate times.", "There is a repeat charge for the same item",
            "I don't recognise a payment on my card", "My refund still hasn't shown up"]
ANGLES = ["physical goods from an online shop", "a concert or event ticket that never came", "food delivery that never arrived",
          "a service that was paid for but never provided", "a parcel the tracking says delivered but they never got",
          "a marketplace seller who stopped responding", "a subscription box that did not arrive", "furniture with a missed delivery"]
STYLES = ["very short (5-10 words)", "one sentence", "two sentences, slightly annoyed", "a question", "informal, typos allowed",
          "non-native English"]

PROMPT = """Write {k} different messages a bank customer types into a support chat. Each one says they PAID for something
that was NOT DELIVERED or NOT PROVIDED, and wants help getting their money back.
Angle: {angle}. Style: {style}.
Match the length and tone of these real support messages (which are about other topics): {examples}
Rules: no merchant names, no amounts, no dates. Vary wording; do not start every message the same way.
Do not mention duplicate charges, unrecognised payments or refunds already promised by the merchant."""


def norm(t: str) -> str:
    return re.sub(r"[^a-z ]", "", t.lower()).strip()


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=300)
    ap.add_argument("--seed", type=int, default=3)
    args = ap.parse_args()
    rng = random.Random(args.seed)
    settings = Settings()
    jobs = [(rng.choice(ANGLES), rng.choice(STYLES)) for _ in range(args.n // 10 + 8)]  # oversample, dedupe later

    def run(job):
        brain = make_llm_brain(settings)
        out = brain.complete(PROMPT.format(k=10, angle=job[0], style=job[1], examples=EXAMPLES), Batch)
        return [(m.strip(), job) for m in out.messages], brain.usage.cost_usd

    with ThreadPoolExecutor(max_workers=8) as pool:
        results = list(pool.map(run, jobs))
    seen, rows = set(), []
    for msgs, _ in results:
        for text, (angle, style) in msgs:
            key = norm(text)
            if key and key not in seen and len(text) < 220:
                seen.add(key)
                rows.append({"text": text, "dispute_type": "not_received", "angle": angle, "style": style,
                             "source": f"synthetic:{settings.model}", "review_status": "unreviewed"})
    rows = rows[: args.n]
    out = ROOT / "data" / "synthetic" / "not_received.jsonl"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("".join(json.dumps(r) + "\n" for r in rows))
    print(f"{len(rows)} unique messages -> {out.relative_to(ROOT)}  cost ${sum(c for _, c in results):.3f}")
    for r in rng.sample(rows, 6):
        print("  -", r["text"])


if __name__ == "__main__":
    main()
